/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "group_entitlements" CASCADE;

DROP TABLE IF EXISTS "user_groups" CASCADE;

DROP TABLE IF EXISTS "group" CASCADE;

CREATE TABLE "group" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NULL);

CREATE UNIQUE INDEX "group_name_i"
  ON "group" ("name");

CREATE TABLE "user_groups" (
  "group_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  CONSTRAINT "group_id_fk"
    FOREIGN KEY ("group_id")
    REFERENCES "group" ("id")
    ON DELETE CASCADE);

CREATE INDEX "user_groups_group_id_i"
  ON "user_groups" ("group_id");

CREATE INDEX "user_groups_index_i"
  ON "user_groups" ("index");

CREATE TABLE "group_entitlements" (
  "group_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "entitlement_id" BIGINT NOT NULL,
  CONSTRAINT "group_id_fk"
    FOREIGN KEY ("group_id")
    REFERENCES "group" ("id")
    ON DELETE CASCADE);

CREATE INDEX "group_entitlements_group_id_i"
  ON "group_entitlements" ("group_id");

CREATE INDEX "group_entitlements_index_i"
  ON "group_entitlements" ("index");

