/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "entitlement" CASCADE;

CREATE TABLE "entitlement" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "code" TEXT NOT NULL,
  "description" TEXT NULL);

CREATE UNIQUE INDEX "entitlement_code_i"
  ON "entitlement" ("code");

