/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user_entitlements" CASCADE;

DROP TABLE IF EXISTS "user_groups" CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "username" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE);

CREATE UNIQUE INDEX "user_username_i"
  ON "user" ("username");

CREATE UNIQUE INDEX "user_email_i"
  ON "user" ("email");

CREATE TABLE "user_groups" (
  "user_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "group_id" BIGINT NOT NULL,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "user" ("id")
    ON DELETE CASCADE);

CREATE INDEX "user_groups_user_id_i"
  ON "user_groups" ("user_id");

CREATE INDEX "user_groups_index_i"
  ON "user_groups" ("index");

CREATE TABLE "user_entitlements" (
  "user_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "entitlement_id" BIGINT NOT NULL,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "user" ("id")
    ON DELETE CASCADE);

CREATE INDEX "user_entitlements_user_id_i"
  ON "user_entitlements" ("user_id");

CREATE INDEX "user_entitlements_index_i"
  ON "user_entitlements" ("index");

