"""Initial migration

Revision ID: d6c4572d8f33
Revises: 
Create Date: 2025-06-01 21:11:05.989139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c4572d8f33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videos',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnails', sa.JSON(), nullable=True),
    sa.Column('localized', sa.JSON(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('raw_snippet', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    # ### end Alembic commands ###
