"""Auto revision

Revision ID: b6e1796d2cbc
Revises: 
Create Date: 2025-06-13 09:26:04.225817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e1796d2cbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
task_type_enum = sa.Enum('YoutubeTask', 'UnknownTask', name='task_type')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_type_enum.create(op.get_bind())
    op.add_column(
        'tasks',
        sa.Column('type', task_type_enum, nullable=False, server_default='UnknownTask')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'type')
    # ### end Alembic commands ###
