version: '3.9'

services:
  beetracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curiousbytes-beetracker
    volumes:
      - .:/app  # ✅ Mount entire root, so run.sh is accessible
    working_dir: /app
    command: ["sh", "run.sh"]  # ✅ Will now find run.sh at /app/run.sh
    ports:
      - "8083:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - curiousnet
    restart: unless-stopped

networks:
  curiousnet:
    external: true