version: "3.9"

services:
  db:
    image: postgres:15
    container_name: beetracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vkandula
      POSTGRES_PASSWORD: vkandula
      POSTGRES_DB: beetracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beetracker_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your-secret-key
      - JWT_REFRESH_SECRET=your-refresh-key
      - ACCESS_TOKEN_EXPIRY=15m
      - REFRESH_TOKEN_EXPIRY=30d
      - DATABASE_URL=postgresql://vkandula:vkandula@db/beetracker
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata: