version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: beetracker-postgres
    environment:
      POSTGRES_USER: beeuser
      POSTGRES_PASSWORD: beepass
      POSTGRES_DB: beetracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata-beetracker:/var/lib/postgresql/data

  postgres-dev:
    image: postgres:15
    restart: always
    container_name: beetracker-postgres-dev
    environment:
      POSTGRES_USER: beeuser
      POSTGRES_PASSWORD: beepass
      POSTGRES_DB: beetracker_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata-beetracker-dev:/var/lib/postgresql/data
  
  postgres-curiousbytes:
    image: postgres:15
    restart: always
    container_name: curiousbytes-postgres
    environment:
      POSTGRES_USER: curioususer
      POSTGRES_PASSWORD: curiouspass
      POSTGRES_DB: curiousbytes
    ports:
      - "5434:5432"
    volumes:
      - pgdata-curiousbytes:/var/lib/postgresql/data

  curiousbytes-frontend:
    build:
      context: ./website/frontend
    container_name: curiousbytes-frontend
    restart: always
    depends_on:
      - curiousbytes-backend
    ports:
      - "5173:5173"
    working_dir: /app

  curiousbytes-backend:
    build:
      context: ./website/backend
    container_name: curiousbytes-backend
    restart: always
    depends_on:
      - postgres-curiousbytes
    environment:
      - DATABASE_URL=postgresql://curioususer:curiouspass@postgres-curiousbytes:5432/curiousbytes
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_PLAYLIST_ID=${YOUTUBE_PLAYLIST_ID}
      - YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
      - YOUTUBE_CACHE_REFRESH_INTERVAL=${YOUTUBE_CACHE_REFRESH_INTERVAL}
    volumes:
      - ./website/backend:/app
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  beetracker:
    build:
      context: ./beetracker-server
    container_name: beetracker
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://beeuser:beepass@postgres:5432/beetracker
      - PYTHONDONTWRITEBYTECODE=1
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_ACCESS_TOKEN_SECRET_KEY=${JWT_ACCESS_TOKEN_SECRET_KEY}
      - JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME:-15m}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME:-30d}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_BUNDLE_ID=${APPLE_BUNDLE_ID}
      - APPLE_P8_CERTIFICATE=${APPLE_P8_CERTIFICATE}
      - APPLE_USE_SANDBOX=${APPLE_USE_SANDBOX:-false}
      - LOAD_TEST_DATA=${LOAD_TEST_DATA:-false}
    volumes:
      - ./beetracker-server:/app
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  beetracker-dev:
    build:
      context: ./beetracker-server
    container_name: beetracker-dev
    restart: always
    depends_on:
      - postgres-dev
    environment:
      - DATABASE_URL=postgresql://beeuser:beepass@postgres-dev:5432/beetracker_dev
      - PYTHONDONTWRITEBYTECODE=1
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - DEV_JWT_ACCESS_TOKEN_SECRET_KEY=${JWT_ACCESS_TOKEN_SECRET_KEY}
      - DEV_JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME:-15m}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME:-30d}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_BUNDLE_ID=${APPLE_BUNDLE_ID}
      - APPLE_P8_CERTIFICATE=${APPLE_P8_CERTIFICATE}
      - APPLE_USE_SANDBOX=${APPLE_USE_SANDBOX:-true}
      - LOAD_TEST_DATA=${LOAD_TEST_DATA:-true}
    volumes:
      - ./beetracker-server:/app
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    depends_on:
      - nginx
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TUNNEL_METRICS=0.0.0.0:2000

volumes:
  pgdata-beetracker:
  pgdata-beetracker-dev:
  pgdata-curiousbytes: