/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user_entitlements" CASCADE;

DROP TABLE IF EXISTS "user_groups" CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS "group_entitlements" CASCADE;

DROP TABLE IF EXISTS "group" CASCADE;

DROP TABLE IF EXISTS "entitlement" CASCADE;

CREATE TABLE "entitlement" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "code" VARCHAR(50) NOT NULL,
  "description" TEXT NULL);

CREATE UNIQUE INDEX "entitlement_code_i"
  ON "entitlement" ("code");

CREATE TABLE "group" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL,
  "description" TEXT NULL);

CREATE UNIQUE INDEX "group_name_i"
  ON "group" ("name");

CREATE TABLE "group_entitlements" (
  "group_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "entitlement_id" BIGINT NULL,
  CONSTRAINT "group_id_fk"
    FOREIGN KEY ("group_id")
    REFERENCES "group" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "entitlement_id_fk"
    FOREIGN KEY ("entitlement_id")
    REFERENCES "entitlement" ("id")
    INITIALLY DEFERRED);

CREATE INDEX "group_entitlements_group_id_i"
  ON "group_entitlements" ("group_id");

CREATE INDEX "group_entitlements_index_i"
  ON "group_entitlements" ("index");

CREATE TABLE "user" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "username" VARCHAR(50) NOT NULL,
  "email" VARCHAR(100) NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE);

CREATE UNIQUE INDEX "user_username_i"
  ON "user" ("username");

CREATE UNIQUE INDEX "user_email_i"
  ON "user" ("email");

CREATE TABLE "user_groups" (
  "user_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "group_id" BIGINT NULL,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "user" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "group_id_fk"
    FOREIGN KEY ("group_id")
    REFERENCES "group" ("id")
    INITIALLY DEFERRED);

CREATE INDEX "user_groups_user_id_i"
  ON "user_groups" ("user_id");

CREATE INDEX "user_groups_index_i"
  ON "user_groups" ("index");

CREATE TABLE "user_entitlements" (
  "user_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "entitlement_id" BIGINT NULL,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "user" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "entitlement_id_fk"
    FOREIGN KEY ("entitlement_id")
    REFERENCES "entitlement" ("id")
    INITIALLY DEFERRED);

CREATE INDEX "user_entitlements_user_id_i"
  ON "user_entitlements" ("user_id");

CREATE INDEX "user_entitlements_index_i"
  ON "user_entitlements" ("index");

