version: "3.9"
services:
  beetracker-dev:
    build:
      context: ./server
    container_name: beetracker-dev
    restart: always
    environment:
      - DATABASE_URL=postgresql://beeuser:beepass@beetracker-postgres-dev:5432/beetracker_dev
      - PYTHONDONTWRITEBYTECODE=1
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - DEV_JWT_ACCESS_TOKEN_SECRET_KEY=${JWT_ACCESS_TOKEN_SECRET_KEY}
      - DEV_JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME:-15m}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME:-30d}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_BUNDLE_ID=${APPLE_BUNDLE_ID}
      - APPLE_P8_CERTIFICATE=${APPLE_P8_CERTIFICATE}
      - APPLE_USE_SANDBOX=${APPLE_USE_SANDBOX:-true}
      - LOAD_TEST_DATA=${LOAD_TEST_DATA:-true}
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - curiousbeenet
      - internal

  beetracker-postgres-dev:
    image: postgres:15
    container_name: beetracker-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: beeuser
      POSTGRES_PASSWORD: beepass
      POSTGRES_DB: beetracker_dev
    volumes:
      - pgdata-beetracker-dev:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pgdata-beetracker-dev:

networks:
  curiousbeenet:
    external: true
  internal: