global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'curiosbytes-frontend'
    static_configs:
      - targets: ['curiousbytes-frontend:5173']
  - job_name: 'curiosbytes-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['curiousbytes-backend:8000']