"""add is_video field to youtube_videos

Revision ID: f61bac5fb904
Revises: ce43739407ad
Create Date: 2025-06-02 10:01:52.497306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61bac5fb904'
down_revision: Union[str, None] = 'ce43739407ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_videos', sa.Column('is_video', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'is_video')
    # ### end Alembic commands ###
