"""Initial full schema

Revision ID: 0a8f637a9b7f
Revises: f7fbde06073b
Create Date: 2025-05-29 17:32:05.994786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8f637a9b7f'
down_revision: Union[str, None] = 'f7fbde06073b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('_other_users_presence_necessary', sa.Boolean(), nullable=True))
    op.drop_column('tasks', '_presence_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('_presence_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', '_other_users_presence_necessary')
    # ### end Alembic commands ###
