"""Initial full schema

Revision ID: 44a66eae4c6a
Revises: fbc75fafeb26
Create Date: 2025-05-29 15:45:21.253637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a66eae4c6a'
down_revision: Union[str, None] = 'fbc75fafeb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('_product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['_product_id'], ['_id'])
    op.add_column('product_infos', sa.Column('_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'product_infos', 'groups', ['_group_id'], ['_id'])
    op.drop_constraint(op.f('products__order_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', '_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('_order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products__order_id_fkey'), 'products', 'orders', ['_order_id'], ['_id'])
    op.drop_constraint(None, 'product_infos', type_='foreignkey')
    op.drop_column('product_infos', '_group_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', '_product_id')
    # ### end Alembic commands ###
