"""Initial full schema

Revision ID: da084b982d78
Revises: 9342a1b294c6
Create Date: 2025-05-29 12:04:44.262002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da084b982d78'
down_revision: Union[str, None] = '9342a1b294c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_infos',
    sa.Column('_group_id', sa.UUID(), nullable=False),
    sa.Column('_average_cycle_length', sa.Integer(), nullable=True),
    sa.Column('_active_period_start_date', sa.Date(), nullable=True),
    sa.Column('_predicted_next_period_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['_group_id'], ['groups._id'], ),
    sa.PrimaryKeyConstraint('_group_id')
    )
    op.drop_table('period_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_info',
    sa.Column('_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('_average_cycle_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_active_period_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('_predicted_next_period_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['_group_id'], ['groups._id'], name=op.f('period_info__group_id_fkey')),
    sa.PrimaryKeyConstraint('_group_id', name=op.f('period_info_pkey'))
    )
    op.drop_table('period_infos')
    # ### end Alembic commands ###
