"""Initial full schema

Revision ID: f409c2dbf529
Revises: 1aa46246472f
Create Date: 2025-05-29 12:55:59.954114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f409c2dbf529'
down_revision: Union[str, None] = '1aa46246472f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders__product_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', '_product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('_product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders__product_id_fkey'), 'orders', 'products', ['_product_id'], ['_id'])
    # ### end Alembic commands ###
