"""Initial full schema

Revision ID: f7fbde06073b
Revises: 44a66eae4c6a
Create Date: 2025-05-29 16:56:21.912535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fbde06073b'
down_revision: Union[str, None] = '44a66eae4c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('_symptom_id', sa.UUID(), nullable=False),
    sa.Column('_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_symptom_id')
    )
    op.create_table('period_symptoms',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_period_entry_id', sa.UUID(), nullable=True),
    sa.Column('_symptom_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['_period_entry_id'], ['period_entries._id'], ),
    sa.ForeignKeyConstraint(['_symptom_id'], ['symptoms._symptom_id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.add_column('period_entries', sa.Column('_period_info_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('period_entries__group_id_fkey'), 'period_entries', type_='foreignkey')
    op.create_foreign_key(None, 'period_entries', 'period_infos', ['_period_info_id'], ['_group_id'])
    op.drop_column('period_entries', '_group_id')
    op.add_column('period_infos', sa.Column('_average_period_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_infos', '_average_period_duration')
    op.add_column('period_entries', sa.Column('_group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'period_entries', type_='foreignkey')
    op.create_foreign_key(op.f('period_entries__group_id_fkey'), 'period_entries', 'groups', ['_group_id'], ['_id'])
    op.drop_column('period_entries', '_period_info_id')
    op.drop_table('period_symptoms')
    op.drop_table('symptoms')
    # ### end Alembic commands ###
