"""Initial full schema

Revision ID: f96a17583c0b
Revises: 49819b8424e4
Create Date: 2025-05-29 01:03:43.551894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96a17583c0b'
down_revision: Union[str, None] = '49819b8424e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calendar_entries', 'tasks', ['_task_id'], ['_id'], use_alter=True)
    op.add_column('orders', sa.Column('_product_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('orders__product_info_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['_product_id'], ['_id'], use_alter=True)
    op.drop_column('orders', '_product_info_id')
    op.drop_column('tasks', '_calendar_entry_id')
    op.add_column('users', sa.Column('_apple_device_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password_hash')
    op.drop_column('users', '_apple_device_token')
    op.add_column('tasks', sa.Column('_calendar_entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('_product_info_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders__product_info_id_fkey'), 'orders', 'product_infos', ['_product_info_id'], ['_id'])
    op.drop_column('orders', '_product_id')
    op.drop_constraint(None, 'calendar_entries', type_='foreignkey')
    # ### end Alembic commands ###
