services:
  services-postgres:
    image: postgres:15
    container_name: services-postgres
    restart: always
    environment:
      POSTGRES_USER: curioususer
      POSTGRES_PASSWORD: curiouspass
      POSTGRES_DB: curiousbytes
    ports:
      - "5432:5432"
    volumes:
      - pgdata-curiousbytes:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pgdata-curiousbytes:
    external: true
    name: curiousbytes-database

networks:
  curiousbeenet:
    external: true
  internal: