"""changed youtube_type field to youtube_videos

Revision ID: 3396b357dcaf
Revises: bce76eb1e426
Create Date: 2025-06-06 12:27:46.134902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import enum

# revision identifiers, used by Alembic.
# op.execute("ALTER TYPE videotype ADD VALUE IF NOT EXISTS 'interview'")
revision: str = '3396b357dcaf'
down_revision: Union[str, None] = 'bce76eb1e426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

class VideoTypeEnum(enum.Enum):
    GateGeneral = "GateGeneral"
    GateStrategy = "GateStrategy"
    GateToppersInterview = "GateToppersInterview"

videotype_enum = sa.Enum(VideoTypeEnum, name="videotype")

def upgrade() -> None:
    """Upgrade schema."""
    videotype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE youtube_videos
        ALTER COLUMN video_type TYPE videotype
        USING video_type::videotype
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_videos', 'video_type',
               existing_type=sa.Enum('GateGeneral', 'GateStrategy', 'GateToppersTalk', name='videotype'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
