"""Add table links

Revision ID: 8bd7a1121039
Revises: 984b347eaee6
Create Date: 2025-07-30 17:19:26.062438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd7a1121039'
down_revision: Union[str, None] = '984b347eaee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blog_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('ref_type', sa.Enum('Video', 'Blog', 'Resource', name='tag_ref_type'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_links')
    op.drop_table('resource_videos')
    op.drop_table('blog_videos')
    op.drop_table('tags')
    # ### end Alembic commands ###
