"""Add blogs, resources, tag_links, and related tables

Revision ID: 984b347eaee6
Revises: 40dee5ef072c
Create Date: 2025-07-30 17:18:35.877929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984b347eaee6'
down_revision: Union[str, None] = '40dee5ef072c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resources', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('resources', sa.Column('title', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('description', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('type', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('resources', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resources', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.drop_column('resources', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('resources', 'scheduled_at')
    op.drop_column('resources', 'created_at')
    op.drop_column('resources', 'is_featured')
    op.drop_column('resources', 'type')
    op.drop_column('resources', 'description')
    op.drop_column('resources', 'title')
    op.drop_column('resources', 'id')
    op.drop_table('blogs')
    # ### end Alembic commands ###
