"""add youtube_type field to youtube_videos

Revision ID: bce76eb1e426
Revises: 6d5fb7d0541f
Create Date: 2025-06-06 12:12:21.111072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce76eb1e426'
down_revision: Union[str, None] = '6d5fb7d0541f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_videos', sa.Column('video_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'video_type')
    # ### end Alembic commands ###
