services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/curiousbytes.in/fullchain.pem:/etc/nginx/certs/cert.pem:ro
      - /etc/letsencrypt/live/curiousbytes.in/privkey.pem:/etc/nginx/certs/key.pem:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - curiousbeenet

networks:
  curiousbeenet:
    external: true